name: Docker Image build

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/al7mino/moon-dice-roller:latest
          
      - name: Deploying using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop moon-dice-roller
            docker system prune -f
            echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io/v2/al7mino/moon-dice-roller/manifests/latest -u ${{ github.actor }} --password-stdin
            docker image pull ghcr.io/al7mino/moon-dice-roller:latest
            docker run -d -e TOKEN=${{ secrets.DISCORD_TOKEN }} --name moon-dice-roller ghcr.io/al7mino/moon-dice-roller:latest